# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wcore', '0001_initial'),
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demowavesservice',
            name='binary_file',
            field=models.ForeignKey(blank=True, help_text="If set, 'Execution parameter' param line:'command' will be ignored", null=True, on_delete=django.db.models.deletion.SET_NULL, to='wcore.ServiceBinaryFile'),
        ),
        migrations.AddField(
            model_name='demowavesservice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_tools', to='demo.ServiceCategory'),
        ),
        migrations.AddField(
            model_name='demowavesservice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demowavesservice',
            name='restricted_client',
            field=models.ManyToManyField(blank=True, help_text='By default access is granted to everyone, you may restrict access here.', related_name='demo_demowavesservice_restricted_services', to=settings.AUTH_USER_MODEL, verbose_name='Restricted clients'),
        ),
        migrations.AddField(
            model_name='demowavesservice',
            name='runner',
            field=models.ForeignKey(help_text='Service job runs adapter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_demowavesservice_runs', to='wcore.Runner'),
        ),
    ]
