# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wcore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demowavesservice',
            options={'ordering': ['name'], 'verbose_name': 'Online Service', 'verbose_name_plural': 'Online Services'},
        ),
        migrations.AlterModelOptions(
            name='demowavessubmission',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='demowavesservice',
            name='binary_file',
            field=models.ForeignKey(blank=True, help_text="If set, 'Execution parameter' param line:'command' will be ignored", null=True, on_delete=django.db.models.deletion.SET_NULL, to='wcore.ServiceBinaryFile'),
        ),
        migrations.AddField(
            model_name='demowavesservice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_tools', to='demo.ServiceCategory'),
        ),
        migrations.AddField(
            model_name='demowavesservice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demowavesservice',
            name='restricted_client',
            field=models.ManyToManyField(blank=True, help_text="Public access is granted to everyone, If status is 'Restricted' you may restrict access to specific users here.", related_name='demo_demowavesservice_restricted_services', to=settings.AUTH_USER_MODEL, verbose_name='Restricted clients'),
        ),
        migrations.AddField(
            model_name='demowavesservice',
            name='runner',
            field=models.ForeignKey(help_text='Service job runs configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_demowavesservice_runs', to='wcore.Runner', verbose_name='Computing infrastructure'),
        ),
        migrations.AddField(
            model_name='demowavessubmission',
            name='binary_file',
            field=models.ForeignKey(blank=True, help_text="If set, 'Execution parameter' param line:'command' will be ignored", null=True, on_delete=django.db.models.deletion.SET_NULL, to='wcore.ServiceBinaryFile'),
        ),
        migrations.AddField(
            model_name='demowavessubmission',
            name='runner',
            field=models.ForeignKey(help_text='Service job runs configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_demowavessubmission_runs', to='wcore.Runner', verbose_name='Computing infrastructure'),
        ),
        migrations.AddField(
            model_name='demowavessubmission',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.WCORE_SERVICE_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='demowavesservice',
            unique_together=set([('api_name', 'version', 'status')]),
        ),
    ]
