# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 11:55
from __future__ import unicode_literals

from django.db import migrations
import waves.wcore.compat


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20170915_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demowavesservice',
            name='description',
            field=waves.wcore.compat.RichTextField(blank=True, help_text='Description (HTML)', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=waves.wcore.compat.RichTextField(blank=True, help_text='Description (HTML)', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicemeta',
            name='description',
            field=waves.wcore.compat.RichTextField(blank=True, help_text='Description (HTML)', null=True, verbose_name='Description'),
        ),
    ]
