# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import waves.models.inputs


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseparam',
            name='related_to',
            field=models.ForeignKey(blank=True, help_text='Input is associated to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependents_inputs', to='waves.BaseParam'),
        ),
        migrations.AlterField(
            model_name='baseparam',
            name='required',
            field=models.NullBooleanField(choices=[(False, 'Not submitted'), (None, 'Optional'), (True, 'Required')], default=True, help_text='Submitted and/or Required', verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='baseparam',
            name='when_value',
            field=models.CharField(blank=True, help_text='Input is treated only for this parent value', max_length=255, null=True, verbose_name='When value'),
        ),
        migrations.AlterField(
            model_name='listparam',
            name='list_elements',
            field=models.TextField(help_text='One Element per line label|value', max_length=500, validators=[waves.models.inputs.validate_list_param], verbose_name='Elements'),
        ),
        migrations.AlterField(
            model_name='repeatedgroup',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_groups', to='waves.Submission'),
        ),
    ]
