# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 08:27
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
import django.contrib.sites.managers
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_countries.fields
import mptt.fields
import uuid
import waves.models.profiles
import waves.models.samples


def setup_default_submission(apps, schema_editor):
    ServiceSubmission = apps.get_model('waves', 'ServiceSubmission')
    Service = apps.get_model('waves', 'Service')
    BaseInput = apps.get_model('waves', 'BaseInput')
    for serv in Service.objects.all():
        # get current submissions if exists
        submission = ServiceSubmission.objects.create(label='default',
                                                      available_online=True,
                                                      available_api=True,
                                                      default=True,
                                                      service=serv,
                                                      api_name="default")
        for inp in BaseInput.objects.filter(service_id=serv.id):
            inp.service = submission
            inp.save()
        serv.save()


def reverse_default_submission(apps, schema_editor):
    ServiceSubmission = apps.get_model('waves', 'ServiceSubmission')
    BaseInput = apps.get_model('waves', 'BaseInput')
    for submission in ServiceSubmission.objects.all():
        for inp in BaseInput.objects.filter(service_id=submission.id):
             inp.service.pk = submission.service.pk
             inp.save()
        submission.delete()


class Migration(migrations.Migration):
    initial = False

    dependencies = [
        ('waves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiprofile',
            name='slug',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='jobinput',
            name='slug',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='joboutput',
            name='slug',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='servicesubmission',
            name='slug',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(setup_default_submission, reverse_default_submission)
    ]
