# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wavesconfiguration',
            options={'verbose_name': 'Application config'},
        ),
    ]
