# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aparam',
            options={'ordering': ['order'], 'verbose_name': 'Param', 'verbose_name_plural': 'Params'},
        ),
        migrations.AlterModelOptions(
            name='booleanparam',
            options={'verbose_name': 'Boolean choice', 'verbose_name_plural': 'Boolean choices'},
        ),
        migrations.AlterModelOptions(
            name='fileinput',
            options={'ordering': ['order'], 'verbose_name': 'File', 'verbose_name_plural': 'Files input'},
        ),
        migrations.AlterModelOptions(
            name='listparam',
            options={'verbose_name': 'List', 'verbose_name_plural': 'Lists'},
        ),
        migrations.AlterModelOptions(
            name='textparam',
            options={'verbose_name': 'Text', 'verbose_name_plural': 'Text'},
        ),
        migrations.AddField(
            model_name='aparam',
            name='regexp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Validation Regexp'),
        ),
        migrations.AlterField(
            model_name='aparam',
            name='cmd_format',
            field=models.IntegerField(choices=[(0, 'Not used'), (2, '-[name] value'), (1, '--[name]=value'), (3, '-[name]'), (5, '--[name]'), (4, 'Posix')], default=2, help_text='Command line pattern', verbose_name='Command line format'),
        ),
        migrations.AlterField(
            model_name='jobinput',
            name='param_type',
            field=models.IntegerField(choices=[(0, 'Not used'), (2, '-[name] value'), (1, '--[name]=value'), (3, '-[name]'), (5, '--[name]'), (4, 'Posix')], default=0, editable=False, null=True, verbose_name='Parameter Type'),
        ),
    ]
