# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adaptorinitparam',
            options={'ordering': ['name'], 'verbose_name': 'Initial param', 'verbose_name_plural': 'Init params'},
        ),
        migrations.AlterField(
            model_name='adaptorinitparam',
            name='prevent_override',
            field=models.BooleanField(default=False, help_text='Prevent override', verbose_name='Prevent override'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='clazz',
            field=models.CharField(help_text='This is the concrete class used to perform job execution', max_length=100, verbose_name='Adaptor object'),
        ),
    ]
