# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 11:50
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
from django.conf import settings

if 'ckeditor' in settings.INSTALLED_APPS:

    class Migration(migrations.Migration):

        dependencies = [
            ('waves', '0001_initial'),
        ]

        operations = [
            migrations.AlterField(
                model_name='baseinput',
                name='description',
                field=ckeditor.fields.RichTextField(blank=True, help_text='Full description (HTML enabled)', null=True, verbose_name='Description'),
            ),
            migrations.AlterField(
                model_name='runner',
                name='description',
                field=ckeditor.fields.RichTextField(blank=True, help_text='Full description (HTML enabled)', null=True, verbose_name='Description'),
            ),
            migrations.AlterField(
                model_name='service',
                name='description',
                field=ckeditor.fields.RichTextField(blank=True, help_text='Full description (HTML enabled)', null=True, verbose_name='Description'),
            ),
            migrations.AlterField(
                model_name='servicecategory',
                name='description',
                field=ckeditor.fields.RichTextField(blank=True, help_text='Full description (HTML enabled)', null=True, verbose_name='Description'),
            ),
            migrations.AlterField(
                model_name='servicemeta',
                name='description',
                field=ckeditor.fields.RichTextField(blank=True, help_text='Full description (HTML enabled)', null=True, verbose_name='Description'),
            ),
            migrations.AlterField(
                model_name='serviceoutput',
                name='description',
                field=ckeditor.fields.RichTextField(blank=True, help_text='Full description (HTML enabled)', null=True, verbose_name='Description'),
            ),
            migrations.AlterField(
                model_name='wavessite',
                name='theme',
                field=models.CharField(choices=[(b'default', b'Default'), (b'amelia', b'Amelia'), (b'cerulean', b'Cerulean'), (b'cosmo', b'Cosmo'), (b'cyborg', b'Cyborg'), (b'flatly', b'Flatly'), (b'journal', b'Journal'), (b'readable', b'Readable'), (b'simplex', b'Simplex'), (b'slate', b'Slate'), (b'spacelab', b'SpaceLab'), (b'united', b'United'), (b'superhero', b'Superhero'), (b'lumen', b'Lumen')], default='flatly', max_length=255),
            ),
        ]
