# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboutput',
            name='optional',
        ),
    ]
