# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0002_auto_20170214_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RunnerInitParam',
        ),
        migrations.AlterUniqueTogether(
            name='submissionoutput',
            unique_together=set([]),
        ),
    ]
