# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0002_init_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesubmission',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Default submission'),
        ),
        migrations.AlterUniqueTogether(
            name='servicemeta',
            unique_together=set([('type', 'title', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='servicesubmission',
            unique_together=set([('service', 'api_name')]),
        ),
    ]
