# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0002_auto_20170125_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='runner',
            new_name='_runner',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='runner',
            new_name='_runner',
        ),
        migrations.AlterField(
            model_name='submission',
            name='label',
            field=models.CharField(default='default', max_length=255, verbose_name='Submission title'),
            preserve_default=False,
        ),
    ]
