# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0002_remove_joboutput_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionoutput',
            name='from_input',
            field=models.ForeignKey(blank=True, help_text='Valuated with input', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_outputs', to='waves.AParam'),
        ),
    ]
