# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0002_auto_20160831_1350'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baseinput',
            unique_together=set([('label', 'name', 'default', 'service')]),
        ),
    ]
