# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0003_auto_20170221_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextParam',
        ),
        migrations.DeleteModel(
            name='WavesConfigVar',
        ),
        migrations.DeleteModel(
            name='WavesSiteConfig',
        ),
        migrations.CreateModel(
            name='TextParam',
            fields=[
            ],
            options={
                'verbose_name': 'Text input',
                'proxy': True,
                'verbose_name_plural': 'Text input',
            },
            bases=('waves.baseparam',),
        ),
    ]
