# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0003_auto_20170125_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='override_runner',
        ),
    ]
