# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0004_remove_submission_override_runner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='_runner',
            new_name='runner',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='_runner',
            new_name='runner',
        ),
    ]
