# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 07:37
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import waves.models.profiles
import waves.models.samples


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0004_service_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiprofile',
            name='picture',
            field=models.ImageField(blank=True, help_text="Users's avatar", null=True, storage=django.core.files.storage.FileSystemStorage(directory_permissions_mode=509, file_permissions_mode=509, location=b'/data/http/www/html/waves/src/data'), upload_to=waves.models.profiles.profile_directory, verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='serviceinputsample',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(directory_permissions_mode=509, file_permissions_mode=509, location=b'/data/http/www/html/waves/src/data'), upload_to=waves.models.samples.service_sample_directory, verbose_name='File'),
        ),
    ]
