# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0004_auto_20160901_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoutput',
            name='from_input_pattern',
            field=models.CharField(help_text='Apply a format to related input value', max_length=100, null=True, verbose_name='Apply format'),
        ),
    ]
