# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0005_input_output_submission'),
    ]

    operations = [
        migrations.RunSQL("UPDATE waves_runner SET clazz='waves.adaptors.GalaxyJobAdaptor' WHERE id='1';"
                          "UPDATE waves_runner SET clazz='waves.adaptors.SGEJobAdaptor' WHERE id='7';"
                          "UPDATE waves_runner SET clazz='waves.adaptors.GalaxyWorkFlowAdaptor' WHERE id='8';"
                          "UPDATE waves_runner SET clazz='waves.adaptors.ShellJobAdaptor' WHERE id='10';"),
    ]
