# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0005_auto_20170125_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptorinitparam',
            name='crypt',
            field=models.BooleanField(default=False, editable=False, verbose_name='Crypted'),
        ),
    ]
