# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0006_update_clazz_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerunnerparam',
            options={'verbose_name': "Service's adaptor init param"},
        ),
        migrations.AlterField(
            model_name='job',
            name='exit_code',
            field=models.IntegerField(default=0, help_text='Job exit code on relative adaptor', verbose_name='Job system exit code'),
        ),
        migrations.AlterField(
            model_name='job',
            name='remote_job_id',
            field=models.CharField(editable=False, max_length=255, null=True, verbose_name='Remote Job ID (on adaptor)'),
        ),
        migrations.AlterField(
            model_name='servicerunnerparam',
            name='param',
            field=models.ForeignKey(help_text='Initial adaptor param', on_delete=django.db.models.deletion.CASCADE, related_name='param_srv', to='waves.RunnerParam'),
        ),
    ]
