# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0006_adaptorinitparam_crypt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='clazz',
            new_name='cmd_parser',
        ),
    ]
