# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0007_auto_20170127_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='label',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='job',
            name='submission',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='service_jobs', to='waves.Submission'),
            preserve_default=False,
        ),
    ]
