# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 12:15
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import waves.models.profiles
import waves.models.samples


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0007_rename_runners_to_adaptors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiprofile',
            name='picture',
            field=models.ImageField(blank=True, help_text="Users's avatar", null=True, storage=django.core.files.storage.FileSystemStorage(directory_permissions_mode=509, file_permissions_mode=509, location=b'/home/marc/git-sources/waves-webapp/data/'), upload_to=waves.models.profiles.profile_directory, verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='serviceinputsample',
            name='dependent_input',
            field=models.ForeignKey(blank=True, help_text='Dependent on another input value', null=True, on_delete=django.db.models.deletion.SET_NULL, to='waves.BaseInput'),
        ),
        migrations.AlterField(
            model_name='serviceinputsample',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(directory_permissions_mode=509, file_permissions_mode=509, location=b'/home/marc/git-sources/waves-webapp/data/'), upload_to=waves.models.samples.service_sample_directory, verbose_name='File'),
        ),
    ]
