# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def update_old_sample(apps, schema_editor):
    ServiceInputSample = apps.get_model('waves', 'ServiceInputSample')
    ServiceSampleDependentsInput = apps.get_model('waves', 'ServiceSampleDependentsInput')
    all_samples = ServiceInputSample.objects.all()
    for sample in all_samples:
        if sample.dependent_input:
            ServiceSampleDependentsInput.objects.create(sample=sample,
                                                        dependent_input=sample.dependent_input,
                                                        set_value=sample.when_value)

def rollback(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0008_auto_20160913_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSampleDependentsInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('set_value', models.CharField(max_length=200, verbose_name='When sample selected, set value to ')),
                ('dependent_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waves.BaseInput')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waves.ServiceInputSample')),
            ],
            options={
                'db_table': 'waves_sample_dependent_input',
            },
        ),
        migrations.RunPython(update_old_sample, rollback),
        migrations.RemoveField(
            model_name='serviceinputsample',
            name='dependent_input',
        ),
        migrations.RemoveField(
            model_name='serviceinputsample',
            name='when_value',
        ),

    ]
