# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-21 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0009_servicesampledependentsinput'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobhistory',
            options={'ordering': ['-timestamp', '-status']},
        ),
    ]
