# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0010_auto_20160921_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='web_on',
            field=models.BooleanField(default=True, help_text='Service is available for web front', verbose_name='Available on WEB'),
        ),
        migrations.AlterField(
            model_name='service',
            name='api_on',
            field=models.BooleanField(default=True, help_text='Service is available for api calls', verbose_name='Available on API'),
        ),
    ]
