# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20170911_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demowavesservice',
            options={'ordering': ['name'], 'verbose_name': 'WAVES Service', 'verbose_name_plural': 'WAVES Services'},
        ),
        migrations.AlterField(
            model_name='demowavesservice',
            name='binary_file',
            field=models.ForeignKey(blank=True, help_text="If set, 'Execution parameter' param line:'command' will be ignored", null=True, on_delete=django.db.models.deletion.SET_NULL, to='wcore.ServiceBinaryFile'),
        ),
    ]
