# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='api_key',
            field=models.CharField(blank=True, help_text="User's waves_api access key", max_length=255, null=True, unique=True, verbose_name='Api key'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='registered_for_api',
            field=models.BooleanField(default=False, help_text='Register for REST API use', verbose_name='Registered for waves_api use'),
        ),
    ]
